### PR TITLE
Adding the ability to define dedicated Kibana clients.

### PR DESCRIPTION
**Pull request by DandyDeveloper**
There's a full discussion on this patch here:

https://github.com/Viasat/opendistro-elastic-community/pull/10

This was completed prior to the helm chart merge. 

This adds the ability to deploy dedicate clients to an existing release.

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
Can I get some eyes on this?

**Comment by alolita** [comment]
@rishabh6788 Added you as reviewer, other community members are welcome to provide review feedback too.

**Comment by weicongs-amazon** [comment]
@DandyDeveloper sorry for the late reply, and thanks for the contribution. have you tested it locally?

**Comment by DandyDeveloper** [comment]
@weicongs-amazon It was at the time but it has been a while, I may have to double check things.

**Comment by weicongs-amazon** [comment]
close this firstly. feel free to reopen it

**Comment by DandyDeveloper** [comment]
You're closing this 6 days after my reply, after taking 4 months of this being open? 

Come in lads, you're better then this. 

Pretty disappointing to have to see this.

**Comment by weicongs-amazon** [comment]
@DandyDeveloper my bad. we mistakenly put a pending flag to this PR, and I didn't check it before closing it. We are just trying to use some new process to manage PRs. Feel very sorry for this. Reopen it.

**Comment by peterzhuamazon** [comment]
Hi @DandyDeveloper any updates on this PR and your local testings?

**Comment by peterzhuamazon** [comment]
Hi @DandyDeveloper it has been 14 days since my last comment and we have not receive any responses.
Therefore, we will close this PR as of now.
Please feel free to re-open it and confirm your tests to this feature so we can go through the next step. Thanks.

**Pull request closed without merging**
