### PR TITLE
Helm: version update

### PR DESCRIPTION
**Pull request by alrf**

### CODE REVIEW

**Comment by DandyDeveloper** [comment]
@alrf Have you tested this thoroughly? Major updates like this typically come with breaking changes.

**Comment by alrf** [comment]
@DandyDeveloper I tested, unlike @rishabh6788. 
Version update should have been checked and tested here:
https://github.com/opendistro-for-elasticsearch/opendistro-build/commit/79976f5dbb895b5ac0b5d83fe64ef833288d9964 but was not.

As result, `helm package .` command creates `opendistro-es-1.3.0.tgz` archive with `imageTag: 1.4.0` inside yaml files due to this misconfiguration.
I just want to fix it.

Moreover, this https://github.com/opendistro-for-elasticsearch/opendistro-build/commit/e89aa262fc72a73fe86a5bb88f498d69f04288e6 commit broke the building of opendistro images (check my comments for that commit).
And I also tested that.

BTW, would be better for project use githab hooks for "base checks" of the builds before merging the commits - at least, compare imageTags and archive, produced by `helm package` command.

**Comment by DandyDeveloper** [comment]
@alrf 

@aetter Can you take a look at this?

**Comment by rishabh6788** [comment]
Version updated to latest. Closing.

**Pull request closed without merging**
