### PR TITLE
update readme to fix #379

### LINKED ISSUE #379: Remove elasticsearch.ssl.transport.enabled:false/true as it has no effect now
In the helm chart readme, 
https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm
is no longer relevant because transport tls is always enabled.

### PR DESCRIPTION
**Pull request by dmpe**
*Issue #, if available:*

https://github.com/opendistro-for-elasticsearch/opendistro-build/issues/379

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @dmpe can you also remove https://github.com/opendistro-for-elasticsearch/opendistro-build/blame/a7a5fbf111483dcb86c14ad34497b96423d12879/helm/README.md#L519

This line is also related to the settings as it is deprecated now.

**Comment by dmpe** [comment]
Thanks, good catch.

**Comment by peterzhuamazon** [comment]
Hi @dmpe sorry to bother you again.
Seems like this is also a miss: https://github.com/opendistro-for-elasticsearch/opendistro-build/blame/6b0feed0d2e801c6441b6164d1441e8acb5902de/helm/README.md#L340

I should do a global search earlier. Sorry about the inconvinience.

Thanks.

**Comment by dmpe** [comment]
Well, I should have done that as well

**Review by gaiksaya — APPROVED** [review]
LGTM. Thanks for the changes

**Review by peterzhuamazon — APPROVED** [review]

**Pull request merged**
