### PR TITLE
Linux tar

### PR DESCRIPTION
**Pull request by mohit0193**
PR for Linux TAR for open distro for elasticsearch

### CODE REVIEW

**Comment by alolita** [comment]
There is a minor conflict that needs to be resolved. Please fix.

**Comment by mohit0193** [comment]
> There is a minor conflict that needs to be resolved. Please fix.

thanks, done. Please merge the PR.

**Comment by alolita** [comment]
Lgtm. Merged.

**Comment by alolita** [comment]
Merged.

**Pull request merged**
