### PR TITLE
allow defining service topology

### PR DESCRIPTION
**Pull request by tareqhs**
replaces https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/650

*Description of changes:*

Allow setting `topologyKeys` in services to define a service topology
https://kubernetes.io/docs/concepts/services-networking/service-topology/

*Test Results:*

Verified manually.

**Note: If this PR is related to Helm, please also update the README for related documentation changes. Thanks.**
**https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/README.md**

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

### CODE REVIEW

**Comment by tareqhs** [comment]
@peterzhuamazon this replaces https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/650

**Comment by tareqhs** [comment]
@peterzhuamazon ping

**Comment by peterzhuamazon** [comment]
Hi @tareqhs thanks for reopening the PR again.
Just one more question, is this topologykeys only for ES, not KIBANA?
Can we also add it for KIBANA?

Thanks.

**Comment by peterzhuamazon** [comment]
Also, could you resolve the conflicts with your commits, and also add logs/screenshots of testing results?

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @tareqhs it has been 7 days since my last comment.
We will close this PR by now.
Please feel free to re-open this PR at any time.
Thanks.

**Pull request closed without merging**
