### PR TITLE
[HELM] Kibana extra containers

### PR DESCRIPTION
**Pull request by rexbut**
*Description of changes:*
User can define extra containers for Kibana

Test Results:

* Deploy using the following chart values :
```
kibana:
  extraInitContainers:
    - name: extra-init-container
      image: busybox
      command: ["/bin/bash", "-c", "env"]

  extraContainers:
    - name: extra-container
      image: busybox
      command: ["/bin/bash", "-c", "sleep infinity & wait"]
```
* Check the containers on the Kibana pod

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by peterzhuamazon** [comment]
Hi @rexbut thanks for this PR about kibana containers.
We will review it within our team

Thanks.

**Review by peterzhuamazon — APPROVED** [review]

**Review by gaiksaya — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
Hi @rexbut Seems there are some conflicts after we merged your #419 PR.
Could you resolve them so we can merge again?
Thanks!

**Comment by rexbut** [comment]
Hi @peterzhuamazon 
I solved the conflict.

**Comment by peterzhuamazon** [comment]
Thanks @rexbut for the contribution. Merged now.

**Pull request merged**
