### PR TITLE
Allow security secret configurations in values.yaml

### PR DESCRIPTION
**Pull request by ewnetu**
This PR simplifies security secrets configurations. It allows users to specify the values of config.yml, action_groups.yml, internal_users.yml, roles.yml, roles_mapping.yml in values.yaml file instead of creating different secrets for each.
I have modified it so that it is backward compatible (and by default disabled) based on the recommendation  from the previous PR. Below is a simple example showing how this can be used.

  ```
securityConfig:
    enabled: true
    config:
      securityConfigSecret: security-configs-secret
      data:
        config.yml: |-
          _meta:
            type: "config"
            config_version: 2
          config:
            dynamic:
              authc:
                basic_internal_auth_domain:
                  description: "Authenticate via HTTP Basic against internal users database"
                  http_enabled: true
                  transport_enabled: true
                  order: 0
                  http_authenticator:
                    type: basic
                    challenge: false
                  authentication_backend:
                    type: internal
             
        internal_users.yml: |-
          _meta:
            type: "internalusers"
            config_version: 2
          admin:
            hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
            reserved: true
            backend_roles:
            - "admin"
            description: "Kibana admin user"

        roles.yml: |-
          _meta:
            type: "roles"
            config_version: 2
          
        roles_mapping.yml: |-
          _meta:
            type: "rolesmapping"
            config_version: 2
          # Define your roles mapping here

          ## Demo roles mapping

          all_access:
            reserved: false
            backend_roles:
            - "admin"
            description: "Maps admin to all_access"

        tenants.yml: |-
          _meta:
            type: "tenants"
            config_version: 2

        action_groups.yml: |-
          _meta:
            type: "actiongroups"
            config_version: 2
```
@weicongs-amazon let me know what you think about the changes made.

### CODE REVIEW

**Comment by weicongs-amazon** [comment]
Thanks for the changes @ewnetu  I think this is good. Have you tested it when this feature is disabled? just wanna have a double confirm before merging, thanks

**Comment by ewnetu** [comment]
> Thanks for the changes @ewnetu I think this is good. Have you tested it when this feature is disabled? just wanna have a double confirm before merging, thanks

Hello @weicongs-amazon, yes, I just went through it and if this feature is disabled (meaning if nothing is set,i.e., if left with the current settings under values.yaml) then it will the normal ( the 'old' configuration) course of action will take effect.

**Comment by weicongs-amazon** [comment]
@ewnetu thanks a lot for the contribution

**Comment by jtackaberry** [comment]
@ewnetu if I'm reading this correctly, this allows Elasticsearch security related configurables to be passed in via the Helm chart where it will create the Secret resources, but for Kibana configuration (notably Elasticsearch credentials for the kibana user), secrets must be pre-created outside the Helm chart?

**Comment by ewnetu** [comment]
> @ewnetu if I'm reading this correctly, this allows Elasticsearch security related configurables to be passed in via the Helm chart where it will create the Secret resources, but for Kibana configuration (notably Elasticsearch credentials for the kibana user), secrets must be pre-created outside the Helm chart?

Hi @jtackaberry , that is right. As you can see from the example above this PR is only for elasticsearch security configs and doesn't include kibana config.

**Comment by lukasmrtvy** [comment]
@ewnetu hey, sorry for digging this, but how is `securityConfigSecret` mounted inside deployment? i didn find single piece of code that is actualy mounting this secret. thanks

**Pull request merged**
